export const SUGGESTED_COMPANIES = [
  "Tata Consultancy Services",
  "Infosys",
  "Reliance Industries",
  "HDFC Bank",
  "Bharti Airtel",
  "Wipro",
];

export const SAMPLE_PITCH_DATA = {
  analysis_id: "analysis_tcs_sample_2026",
  resultId: "analysis_tcs_sample_2026",
  client: {
    name: "Tata Consultancy Services",
    industry: "Information Technology / Software Services",
    company_size: "615,000+ employees",
    revenue: null,
    revenue_formatted: "Not publicly disclosed",
    employees: 615000,
    employees_formatted: "615,000",
  },
  executive_summary:
    "This executive risk analysis evaluates corporate health and liability underwriting terms for Tata Consultancy Services. By indexing verified brochure wordings across leading insurers, Marsh has benchmarked prevailing terms to eliminate proportionate room rent deductions, institute day-one pre-existing disease waivers, and expand accredited cashless network access.",
  financial_snapshot: {
    current_coverage: 10000000.0,
    current_coverage_formatted: "₹1.0 Cr",
    estimated_exposure: 12500000.0,
    estimated_exposure_formatted: "₹1.25 Cr",
    coverage_gap: 2500000.0,
    coverage_gap_formatted: "₹25 L",
    uninsured_exposure: 2500000.0,
    uninsured_exposure_formatted: "₹25 L",
    coverage_percentage: 80.0,
    data_available: true,
  },
  risk_exposure: [
    {
      category: "Cyber & Technology",
      exposure: 3500000.0,
      exposure_formatted: "₹35 L",
      percentage: 28,
      risk_level: "Elevated",
      data_available: true,
    },
    {
      category: "Operational Continuity",
      exposure: 4000000.0,
      exposure_formatted: "₹40 L",
      percentage: 32,
      risk_level: "High",
      data_available: true,
    },
    {
      category: "People & Workforce",
      exposure: 3000000.0,
      exposure_formatted: "₹30 L",
      percentage: 24,
      risk_level: "Elevated",
      data_available: true,
    },
    {
      category: "Regulatory & Compliance",
      exposure: 2000000.0,
      exposure_formatted: "₹20 L",
      percentage: 16,
      risk_level: "Controlled",
      data_available: true,
    },
  ],
  coverage_analysis: [
    {
      category: "Room Rent Limits",
      current: "1% of Sum Insured / Day",
      benchmark: "Single Private A/C Room (No Sub-limit)",
      gap: "Proportionate deduction penalty on surgical costs",
      source: "HDFC Ergo Health, p.6",
      page: 6,
    },
    {
      category: "Maternity & Newborn Cover",
      current: "₹50,000 Normal / ₹75,000 C-Section",
      benchmark: "₹75,000 Normal / ₹1,00,000 C-Section",
      gap: "Sub-limit shortfall per delivery event",
      source: "HDFC Ergo Health, p.9",
      page: 9,
    },
    {
      category: "Pre-Existing Disease Waiting",
      current: "24-36 Months statutory waiting",
      benchmark: "0 Months (Waived from Day 1)",
      gap: "Waiting period exclusion gap for active associates",
      source: "Care Health Insurance, p.4",
      page: 4,
    },
    {
      category: "Cashless Network Density",
      current: "8,500 Hospitals",
      benchmark: "12,000+ Accredited Hospitals",
      gap: "Cashless access gap in Tier 2/3 locations",
      source: "HDFC Ergo Health, p.14",
      page: 14,
    },
    {
      category: "Mandatory Co-payment",
      current: "10% Co-pay on dependent parents",
      benchmark: "0% Co-pay (Nil)",
      gap: "Out-of-pocket employee co-pay friction at discharge",
      source: "Care Health Insurance, p.2",
      page: 2,
    },
  ],
  policy_audit: {
    total_clauses: 8,
    matched_clauses: 7,
    review_clauses: 1,
    coverage_gaps: 0,
    match_percentage: 87.5,
  },
  clauses: [
    {
      clause: "Zero Room Rent Sub-limits: Coverage extends up to Single Private A/C Room without proportionate deduction penalties on associated surgical charges.",
      current_wording: "Section 4.1 Room Rent & ICU Charges: In the event of hospitalization, the Company shall indemnify the actual room boarding and nursing charges up to Single Private A/C Room category without any proportionate deduction on associated medical expenses.",
      benchmark_wording: "Section 4.1 Room Rent & ICU Charges: In the event of hospitalization, the Company shall indemnify the actual room boarding and nursing charges up to Single Private A/C Room category.",
      similarity_score: 0.98,
      status: "Verified",
      source: "HDFC Ergo Health Insurance",
      page: 6,
    },
    {
      clause: "Comprehensive Maternity Benefit up to ₹75,000 for normal and ₹1,00,000 for caesarean section, including immediate day-one newborn child protection.",
      current_wording: "Special Endorsement - Maternity Benefits: Sum Insured per delivery shall be capped at INR 75,000 for Normal Delivery and INR 1,00,000 for Caesarean Section. Newborn child is covered from birth till the policy expiry date up to the maternity limit.",
      benchmark_wording: "Special Endorsement - Maternity Benefits: Sum Insured per delivery shall be capped at INR 75,000 for Normal Delivery and INR 1,00,000 for Caesarean Section.",
      similarity_score: 0.95,
      status: "Verified",
      source: "HDFC Ergo Health Insurance",
      page: 9,
    },
    {
      clause: "Complete Waiver of Pre-Existing Disease (PED) Waiting Periods from Day 1 for all full-time corporate associates and enrolled dependents.",
      current_wording: "Group Policy Schedule Clause 2.3 - Corporate Waiver: The standard 24/36 months waiting period for Pre-Existing Diseases stands deleted ab-initio for all eligible enrolled members and their declared dependents.",
      benchmark_wording: "Group Policy Schedule Clause 2.3 - Corporate Waiver: The standard 24/36 months waiting period for Pre-Existing Diseases stands deleted ab-initio.",
      similarity_score: 0.97,
      status: "Verified",
      source: "Care Health Insurance",
      page: 4,
    },
    {
      clause: "Over 12,000+ empaneled cashless network hospitals with priority Green Channel discharge assistance.",
      current_wording: "Network Hospital Guidelines: Insured members may avail cashless hospitalization across 12,000+ empaneled healthcare facilities nationwide with priority desk assistance.",
      benchmark_wording: "Network Hospital Guidelines: Insured members may avail cashless hospitalization across 12,000+ empaneled healthcare facilities nationwide.",
      similarity_score: 0.94,
      status: "Verified",
      source: "HDFC Ergo Health Insurance",
      page: 14,
    },
    {
      clause: "Marsh is the world's leading risk adviser and insurance broker, stewarding over $110B in global placed premiums.",
      current_wording: "Marsh McLennan (NYSE: MMC) is the world's leading professional services firm in the areas of risk, strategy and people, with annual revenue of $23 billion and over $110B in placed insurance premiums globally.",
      benchmark_wording: "Marsh McLennan is the world's leading professional services firm in the areas of risk, strategy and people.",
      similarity_score: 0.99,
      status: "Verified",
      source: "Marsh McLennan Corporate Disclosures",
      page: 1,
    },
    {
      clause: "Dedicated enterprise escalation desk with a 98.4% first-pass claims settlement turnaround across corporate group health accounts.",
      current_wording: "Target internal SLA for enterprise accounts specifies 98% turnaround within 48 hours for cashless pre-authorization, subject to third-party administrator documentation.",
      benchmark_wording: "Target internal SLA for enterprise accounts specifies 98% turnaround within 48 hours for cashless pre-authorization.",
      similarity_score: 0.79,
      status: "Review",
      source: "Marsh India Enterprise SLA",
      page: 4,
    },
    {
      clause: "Direct REST API integrations with corporate HRMS systems and primary TPA pre-authorization gateways, eliminating employee out-of-pocket delays.",
      current_wording: "API connector architecture supports direct REST webhook synchronization between corporate HRMS (Workday, Darwinbox, SAP SuccessFactors) and primary TPA claims servers.",
      benchmark_wording: "API connector architecture supports direct REST webhook synchronization between corporate HRMS and primary TPA claims servers.",
      similarity_score: 0.92,
      status: "Verified",
      source: "Marsh Digital Advisory Architecture",
      page: 2,
    },
    {
      clause: "Tata Consultancy Services employs over 615,000 associates globally across 55 countries, representing one of the largest corporate workforces in India.",
      current_wording: "Tata Consultancy Services Limited is an Indian multinational information technology services and consulting company headquartered in Mumbai, part of the Tata Group, employing over 615,000 people across 55 countries.",
      benchmark_wording: "Tata Consultancy Services Limited employs over 615,000 people across 55 countries.",
      similarity_score: 0.96,
      status: "Verified",
      source: "Wikipedia / Annual Disclosures",
      page: 1,
    },
  ],
  historical_data: [],
  scenario_analysis: [
    {
      scenario: "Base Case",
      label: "Scenario estimate",
      description: "Standard annual corporate healthcare claims trajectory based on historical loss ratio.",
      estimated_loss: 8750000.0,
      estimated_loss_formatted: "₹87.5 L",
      modeled_coverage: 10000000.0,
      modeled_coverage_formatted: "₹1.0 Cr",
      net_uninsured: 0.0,
      net_uninsured_formatted: "₹0 (Fully indemnified)",
    },
    {
      scenario: "Stress Case (+25% Medical Volatility)",
      label: "Scenario estimate",
      description: "Inflationary spike in high-cost ICU, surgical, and multi-location viral hospitalizations.",
      estimated_loss: 12500000.0,
      estimated_loss_formatted: "₹1.25 Cr",
      modeled_coverage: 10000000.0,
      modeled_coverage_formatted: "₹1.0 Cr",
      net_uninsured: 2500000.0,
      net_uninsured_formatted: "₹25 L",
    },
    {
      scenario: "Severe Case (+50% Catastrophic Event)",
      label: "Scenario estimate",
      description: "Concurrent epidemic surge combined with severe critical illness and complex surgical claims.",
      estimated_loss: 18750000.0,
      estimated_loss_formatted: "₹1.88 Cr",
      modeled_coverage: 10000000.0,
      modeled_coverage_formatted: "₹1.0 Cr",
      net_uninsured: 8750000.0,
      net_uninsured_formatted: "₹87.5 L",
    },
  ],
  executive_insight:
    "Current coverage represents 80.0% of modeled exposure under benchmark terms. The policy audit evaluated 8 distinct coverage claims, with 7 verified against cited policy text and 1 clause flagged for advisor review.",
  sources: [
    { name: "HDFC Ergo Health Insurance", type: "Policy Brochure" },
    { name: "Care Health Insurance", type: "Policy Brochure" },
    { name: "Aditya Birla Health Insurance (ABHI)", type: "Policy Brochure" },
    { name: "Niva Bupa Health Insurance", type: "Policy Brochure" },
  ],
  pitch: {
    companyName: "Tata Consultancy Services",
    recommended: "HDFC Ergo Health Insurance",
    slides: [
      {
        id: "slide_1",
        title: "Executive Profile & Tailored Risk Landscape",
        claims: [
          {
            id: "claim_profile_1",
            type: "profile_claim",
            text: "Tata Consultancy Services employs over 615,000 associates globally across 55 countries.",
            sourceInsurer: "Wikipedia / Annual Disclosures",
            sourcePage: 1,
          },
        ],
      },
      {
        id: "slide_2",
        title: "Why Marsh McLennan: Strategic Placement & Claims Advocacy",
        claims: [
          {
            id: "claim_why_1",
            type: "context_claim",
            text: "Marsh is the world's leading risk adviser and insurance broker, stewarding over $110B in global placed premiums.",
            sourceInsurer: "Marsh Corporate Disclosures",
            sourcePage: 1,
          },
        ],
      },
      {
        id: "slide_3",
        title: "Curated Policy Benefits & Verifiable Quantitative Terms",
        claims: [
          {
            id: "claim_ben_1",
            type: "policy_claim",
            text: "Zero Room Rent Sub-limits: Coverage extends up to Single Private A/C Room without proportionate deduction penalties.",
            sourceInsurer: "HDFC Ergo Health Insurance",
            sourcePage: 6,
          },
        ],
      },
      {
        id: "slide_4",
        title: "Underwriting Comparator & Recommended Placement",
        claims: [],
        comparatorTable: {
          ranking: [
            { insurer: "HDFC Ergo Health Insurance", score: 0.94 },
            { insurer: "Care Health Insurance", score: 0.88 },
          ],
          rows: [
            {
              key: "roomRent",
              criterion: "Room Rent Sub-limits",
              byInsurer: {
                "HDFC Ergo Health Insurance": { score: 0.95, value: "No sub-limit / Single Pvt AC" },
                "Care Health Insurance": { score: 0.90, value: "Up to 1% of Sum Insured" },
              },
            },
          ],
        },
      },
    ],
  },
  auditReport: {
    overallStatus: "PASS - GOLD CERTIFIED",
    confidenceScore: 94,
    summary: { verified: 7, flagged: 1, untraceable: 0 },
    advisorGuidance:
      "All quantitative claims have been cross-checked against active policy wordings in the Marsh document repository. Numeric limits exhibit high semantic precision. Approved for corporate presentation.",
    claims: [],
  },
};
